### ISSUE TITLE
Duplicate labels for application_id and application_name

### ISSUE THREAD

**Issue by mchabane** [cloudfoundry/firehose_exporter#105]
Hello,

We are on a tanzu application plateform, and we are using the metric registrar to generate customized metrics in our applications.

When we create customized metrics and we set labels "application_id" and "application_name", those label appears twice in the firehose exporter metrics, and it make the firehose exporter prometheus target down, due to duplicate labels.
If we do not set those labels, they do not appear at all.
If set them with an other name, like "applicationId", it appears once as expected.

**Comment by mchabane** [comment]
I think that the issue is due to the presetLabels function in converts.go
https://github.com/bosh-prometheus/firehose_exporter/blob/master/metricmaker/converters.go

**Comment by benjaminguttmann-avtq** [comment]
What I find interesting is, that if you do not set the labels at all, that they do not appear at all, because of the converters I would think it adds them all the time. 
Will try to work myself through that and see what I can do... and how I can reproduce it to fix it :D

**Comment by mchabane** [comment]
We found a temporary workarroud, we set set app_id and app_name, ans it's generate application_id ans application_name.
If application_id and application_name was add everytime, it will be a good solution.

**Comment by mchabane** [comment]
Hello,
the issue is still current.

**Comment by mchabane** [comment]
Hello,
the issue is still current.
